### ISSUE TITLE
The performance of VAT algorithm is much lower.

### ISSUE THREAD

**Issue by LongLong-Jing** [perrying/realistic-ssl-evaluation-pytorch#1]
@perrying 

Thanks for your implementation. I trained the VAT algorithm no the CIFAR10 datasets with the default parameters. However, it got 24.5% error rate on CIFAR10 dataset which is around 11% lower than the results that you reported in the table. Can I reproduce all the results in the table with default parameters?

**Comment by perrying** [comment]
Hi, LongLong-Jing!

All the results can be reproduced with default parameters.

You might have trained the model with CIFAR10 1k labels. (It means `python build_dataset.py --dataset cifar10`)
Did you run `python build_dataset.py --dataset cifar10 --nlabels 4000`
and `python train.py --dataset cifar10 --alg VAT`?

**Comment by LongLong-Jing** [comment]
Hi @perrying,

Thanks for your very quick response. Yes. I checked the parameters and found that I used 1k labels. How many labeled images should I use to reproduce the results in the table?

**Comment by perrying** [comment]
You should use 4k labels for CIFAR10 and 1k labels for SVHN.

**Comment by LongLong-Jing** [comment]
Thanks!
